open("/Users/shruthibalachandra/Desktop/FixedNuclie/2024-07-09-BM_Fixed_H2Av_loading_11-1-2/NCN2.tif");
selectImage("NCN2.tif");
run("Duplicate...", "duplicate");
run("Gaussian Blur 3D...", "x=5 y=5 z=1");
setAutoThreshold("Otsu dark");
//run("Threshold...");
setOption("BlackBackground", true);
run("Convert to Mask", "method=Otsu background=Dark calculate black");
run("Erode", "stack");
run("Dilate", "stack");
run("Open", "stack");
run("Close-", "stack");
run("Fill Holes", "stack");
run("Set Measurements...", "area mean shape integrated stack display redirect=None decimal=3");
run("Analyze Particles...", "size=100-Infinity show=Masks display exclude clear include overlay add stack");
saveAs("Tiff", "/Users/shruthibalachandra/Desktop/FixedNuclie/2024-07-09-BM_Fixed_H2Av_loading_11-1-2/Mask of NCN2.tif");
close();
selectImage("NCN2.tif");
close();
open("/Users/shruthibalachandra/Desktop/FixedNuclie/2024-07-09-BM_Fixed_H2Av_loading_11-1-2/NCN2.tif");
selectImage("NCN2.tif");
roiManager("Measure");
roiManager("Save", "/Users/shruthibalachandra/Desktop/FixedNuclie/2024-07-09-BM_Fixed_H2Av_loading_11-1-2/NCN2_ROI.zip");
Table.deleteRows(0, 13);
saveAs("Results", "/Users/shruthibalachandra/Desktop/FixedNuclie/2024-07-09-BM_Fixed_H2Av_loading_11-1-2/NCN2.csv");
Table.deleteRows(0, 13);
